name: blog_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  supabase_flutter: ^2.9.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dotted_border: ^3.1.0
  image_picker: ^1.2.0
  uuid: ^4.5.1
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.7.2
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  http: ^1.5.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  timeago: ^3.2.2
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.0.0
  url_launcher: ^6.3.2
  lottie: ^3.3.1
  percent_indicator: ^4.2.5
  flutter_native_splash: ^2.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_generative_ai: ^0.4.7
flutter:
  uses-material-design: true
  
  # Material Icons are included by default with Flutter
  # No need to manually include them unless using custom icon fonts
  
  # Uncomment and use this if you have custom icon fonts
  # fonts:
  #   - family: YourCustomIconFont
  #     fonts:
  #       - asset: assets/fonts/your_icon_font.ttf
  
  # Ensure you have the assets directory declared
  assets:
    - assets/images/  # If you have any images
    - assets/fonts/  # If you have any custom fonts
    - assets/lottie/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/lottie/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/lottie/app_logo.png
  android_12:
    image: assets/lottie/app_logo.png
    color: "#FFFFFF"

